language: java
jdk:
  - oraclejdk7
script: mvn clean verify
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_failure: "cat /home/travis/build/cderoove/damp.ekeko/EkekoTests/target/work/data/.metadata/.log"
